apiVersion: apps/v1
kind: StatefulSet # Using StatefulSet for stable storage for slashing protection
metadata:
  name: validator
spec:
  serviceName: validator
  replicas: 1 # Typically 1 validator client instance per node setup
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      serviceAccountName: validator
      terminationGracePeriodSeconds: 60
      volumes:
      - name: jwtsecret-volume
        secret:
          secretName: jwtsecret
          defaultMode: 0o400
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim

      initContainers:
      - name: wait-for-beacon
        image: busybox:1.36
        command: [ 'sh', '-c', 'until nc -z -w 2 beacon-0.beacon 5052; do echo waiting for beacon; sleep 2; done;' ]

      containers:
      - name: validator
        image: sigp/lighthouse:latest-unstable
        command:
        - lighthouse
        - vc # validator_client
        - --debug-level=info
        - --testnet-dir=/data/config
        - --validators-dir=/data/validator-keys/keys
        - --secrets-dir=/data/validator-keys/secrets
        - --init-slashing-protection # Initialize slashing protection DB
        - --beacon-nodes=http://beacon-0.beacon:5052
        - --suggested-fee-recipient=$(FEE_RECIPIENT)
        # No ports exposed by default validator client typically
        envFrom:
        - configMapRef:
            name: env-vars # Load FEE_RECIPIENT etc.
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
        - name: jwtsecret-volume
          mountPath: "/secret"
          readOnly: true
