apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jwt-secret
spec:
  provider: aws
  parameters:
    region: "ap-southeast-1"
    objects: |
      - objectName: "jwtSecret" # The name or ARN of your secret in Secrets Manager
        objectType: "secretsmanager"
        filePermission: "0400"
        # Optional: specify a jmesPath to extract specific key-value pairs from a JSON secret
        jmesPath:
        - path: "jwtSecret"
          objectAlias: "jwtsecret" # Alias to name the file in the mounted volume
          filePermission: "0400"
      # - objectName: "another-secret-name"
      #   objectType: "secretsmanager"
