apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: geth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: geth
subjects:
- kind: ServiceAccount
  name: geth
  namespace: ethereum-l1
