apiVersion: v1
kind: Service
metadata:
  labels:
    pod: geth-0
    type: p2p
  name: geth-0
spec:
  sessionAffinity: None
  type: NodePort
  selector:
    app: geth
    statefulset.kubernetes.io/pod-name: geth-0
  ports:
  - name: p2p-tcp
    nodePort: 31100
    port: 30303
    protocol: TCP
    targetPort: p2p-tcp
  - name: p2p-udp
    nodePort: 31100
    port: 30303
    protocol: UDP
    targetPort: p2p-udp
