apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: geth
spec:
  endpoints:
  - interval: 15s
    path: /debug/metrics/prometheus
    port: metrics
  # namespaceSelector:
  #   matchNames:
  #   - ethereum-l1
  selector:
    matchLabels:
      app: geth
