apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: beacon-read-services
subjects:
- kind: ServiceAccount
  name: beacon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-reader
