---
apiVersion: v1
kind: Service
metadata:
  name: beacon-0
  labels:
    pod: beacon-0
    type: p2p
spec:
  sessionAffinity: None
  type: NodePort
  ports:
  - name: p2p-tcp
    nodePort: 31300
    port: 9000
    protocol: TCP
    targetPort: p2p-tcp
  - name: p2p-udp
    nodePort: 31300
    port: 9000
    protocol: UDP
    targetPort: p2p-udp
  selector:
    app: beacon
    statefulset.kubernetes.io/pod-name: beacon-0
