---
apiVersion: v1
kind: Service
metadata:
  name: beacon-0
  labels:
    type: p2p
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: p2p-tcp
    port: 9000
    protocol: TCP
    targetPort: p2p-tcp
  - name: p2p-udp
    port: 9000
    protocol: UDP
    targetPort: p2p-udp
  selector:
    app: beacon
    statefulset.kubernetes.io/pod-name: beacon-0
